### ISSUE TITLE
add repo button is adding an old version (2.5) of Scrypted

### ISSUE THREAD

**Issue by thomas-svrts** [dshafik/haos-addon-scrypted#1]
Hi,

I used your addon to install Scrypted.
Because I used the button on your readme, I added your repo (github.com/dshafik/haos-addons) to my haos 

But in that main github repo you added a nested link to a specific GIT version (b84a846). could you please nest it at /main level?
I'm now stuck on version 0.2.5, want to upgrade to 0.3.3 which is in your main branch.

![image](https://user-images.githubusercontent.com/81048302/199561694-95ecaa01-cbf0-476a-b87f-9c08ae8fa9cd.png)

**Comment by dshafik** [comment]
Unfortunately, git doesn't support this. It has to be updated manually and I forgot to push the change. I have updated the main repo to update it. I will also check later to see if there has been a new update since 0.3.3.

Ideally this would all be automated, so I'll try to put some work into that, so that it always keeps track both in the main repo, and of scripted itself.

**Comment by dshafik** [comment]
FYI: I've added a Github Action to automatically update this repo every night to the latest Scrypted version in #4
